### PR TITLE
Add xdg capabilities to directories.

### PR DESCRIPTION
**Pull request by edfloreshz**
This PR implements some of the capabilities present in the [`xdg`](https://crates.io/crates/xdg) crate.

## Summary
The `directories` crate is now capable of finding, getting and placing files in the `config`, `data`, `cache`, `state` and `runtime` directories, as well as creating directories.

### Directory creation
```rust
if let Some(base_dirs) = BaseDirs::new() {
    base_dirs.create_config_directory(PathBuf::from(NAME)));
}
```

### File manipulation
```rust
let project = directories::ProjectDirs::from_path()?;

if let Some(proj_dirs) = ProjectDirs::from_path(PathBuf::from(NAME)) {
    if let Ok(path) = project.place_config_file(PathBuf::from(format!("{CONFIG_NAME}.ron"))) {
        let mut f = File::create(path)?;
        let ron = ron::ser::to_string_pretty(&self, Default::default())?;
        f.write_all(ron.as_bytes())?;
        Ok(())
    } else {
        bail!("failed to save config file.")
    }
    
    let config_file_path = project.find_config_file(PathBuf::from(format!("{CONFIG_NAME}.ron")));
}
```

## Details
A new `extensions` folder was created containing three new files:
| File      | Description |
| ---------------------- | -------------------------- |
| `base_ext.rs`      | Contains the `BaseDirsExt` trait, which is implemented by `BaseDirs`.           |
| `project_ext.rs`  | Contains the `ProjectDirsExt` trait, which is implemented by `ProjectDirs`.   |
| `helpers.rs`        | Contains functions that help with the implementation of the new traits.      |

### CODE REVIEW

**Comment by soc** [comment]
Hey @edfloreshz, I'm not sure what's the motivation of adding this code to the library, especially given the design goals:

> This library does not create directories or check for their existence. The library only provides information on what the path to a certain directory should be.
> How this information is used is a decision that developers need to make based on the requirements of each individual application.

The code in the PR appears to be pretty standard file manipulation stuff, why would this need to be integrated with this library?

**Comment by edfloreshz** [comment]
Hey @soc, I was unaware of the design goals, my apologies.

The main motivation behind these changes was integrating the library with [`cosmic-theme`](https://github.com/pop-os/cosmic-theme) and [`libcosmic`](https://github.com/pop-os/libcosmic), we were previously using the `xdg` crate, which implements these methods but it's not compatible with Windows and macOS, and we were hoping to implement them here as well.

If this is not possible, we could implement a separate library for our use case.

Let me know your thoughts...

**Comment by soc** [comment]
I'd prefer not complicating directories any further, as this has knock-on effects on a lot of other things.

I'd recommend adding those extension functions to your code, as I'd expect those functions take cosmic-specific arguments anyway. That way you can leverage the functionality of directories while having full control over the cosmic-specific bits and pieces.

Does this sound good?

**Comment by edfloreshz** [comment]
Sure thing! I understand.

FYI, these functions are not cosmic-specific, they're useful for anyone who wants to interact with the directories to crate files or directories easily.

Thanks for the feedback, I'll close this PR.

**Pull request closed without merging**
